### ISSUE TITLE
Current date on schedule page seems a bit lost

### ISSUE THREAD

**Issue by Bukama** [nipafx/nipafx.dev#11]
At the top of the schedule page the current date is printed without any context. So it gets somehow lost and (at least I) asked myself: Why is the date printed there? Took me a while that it should be  (is the) current date and most probably is placed there to help the viewer to orientate (which events have passed, which will come)

![currentdate](https://user-images.githubusercontent.com/4354359/94991256-29329400-0582-11eb-9334-a89efb0d63d3.png)

**Comment by nipafx** [comment]
Every post/page/etc. has the date of its last update in that spot and I see no reason to make an exception for the schedule. Do you think I should?

**Comment by Bukama** [comment]
Didn‘t notice the date on all the other sites 😂

**Comment by nipafx** [comment]
😹 Ok, I'll close it, then.

**Comment by nipafx** [comment]
😹 Ok, I'll close it, then.
