### ISSUE TITLE
Content issues on courses page / submenu

### ISSUE THREAD

**Issue by Bukama** [nipafx/nipafx.dev#14]
I see three issues on the courses page / submenu

* When going throw the "courses" submenu there are four entries (in house, conferences, remote, online) , but on the page itself you only speak of three (in house, conferences, remote). If you wan't to distinguish between remote (like online / virtual but for only closes circle) and online (online, but for public) you should mentioned the "online" also on the courses talk. If not then remove the "online" point (for firms who want to hire you "remote" is more they are looking for) 
* all submenus link to the same page and its content: So why is there even a submenu?
*  I suggest to reorder the entries from "private" to "public", meaning: `In house > remote > conferences > online` 

![courses](https://user-images.githubusercontent.com/4354359/94991590-7879c400-0584-11eb-8d3a-33abb31b1ea5.png)

**Comment by nipafx** [comment]
Some problems solve themselves. Since I'm no longer for hire, I don't need to fix this. 😁
