### ISSUE TITLE
Broken windows

### ISSUE THREAD

**Issue by nipafx** [nipafx/nipafx.dev#6]
The [site is online](https://nipafx.dev) 🥳  and I'm sure there are lots of small things that didn't quite work out. If you find any, reply here and I will work through them ASAP. Thanks!

PS: Don't mind the `TODO`s - I am aware of them. 😊

**Comment by Bukama** [comment]
When clicking on courses console logs errors

![Uploading courses404.png…]()

**Comment by Bukama** [comment]
Same for code

![Uploading code404.png…]()

**Comment by nipafx** [comment]
Superseeded by all the other issues... 😃
