### ISSUE TITLE
Navigation can't read property styles

### ISSUE THREAD

**Issue by Bukama** [nipafx/nipafx.dev#7]
It seems the navigation has problems reading some "style" property:

![code404](https://user-images.githubusercontent.com/4354359/94990953-0acb9900-0580-11eb-8937-716b4756ef57.png)
![courses404](https://user-images.githubusercontent.com/4354359/94990956-0bfcc600-0580-11eb-9ff5-ddaaff411b28.png)
[nipafx.dev-1601725894862.log](https://github.com/nipafx/nipafx.dev/files/5321602/nipafx.dev-1601725894862.log)

**Comment by Bukama** [comment]
Sometheres there are errors for "eventlistener" and some other properties logged to console.

**Comment by nipafx** [comment]
I can't reproduce the missing styles - I presume this happened because some of the links pointed to non-existing pages. Can you try to reproduce that?

I see the JS errors when handling events for animating menus - I track that in #16.

**Comment by Bukama** [comment]
> I can't reproduce the missing styles - I presume this happened because some of the links pointed to non-existing pages. Can you try to reproduce that?
> 
> I see the JS errors when handling events for animating menus - I track that in #16.

I think what I describe here, is what you described in #16. As you most probably understand your own words in #16 better than this I'll close this here.

**Comment by nipafx** [comment]
Oh, now I see that this is the same error. What the...?! I somehow misread the screenshots you posted.

**Comment by nipafx** [comment]
Technically, it's _duplicated_, not a _duplicate_.
