### ISSUE TITLE
Consider changing the code font

### ISSUE THREAD

**Issue by nipafx** [nipafx/nipafx.dev#83]
Not everybody seems to like the code font ([example](https://twitter.com/_I_NTE_R_/status/1316111359902396423)). Maybe it needs to be replaced? If so, [JetBrains Mono](https://www.jetbrains.com/lp/mono/) is very high up on the list.

**Comment by nipafx** [comment]
I gave [JetBrains Mono a try](https://github.com/nipafx/nipafx.dev/commit/20e8c9fa0dcff84b97fcddac85b1745041c33694):

* taglets look unbearably bland - not "code-y" at all
* similarly for source code
* source code more readable

I think the latter is mostly the case because JetBrains Mono is slimmer.

**Comment by Bukama** [comment]
For tags I like both of them, for source code `JetBrains Mono` is more readable.
In the end you should decide what you like more as it is your side and not the product of anyone else.

Side note (which you have already covered, I guess): You should consider the licence of the font.

**Comment by nipafx** [comment]
Thanks for the feedback, I appreciate it.

[JetBrains Mono is Apache 2.0 licensed.](https://www.jetbrains.com/lp/mono/#license)

**Comment by nipafx** [comment]
I've went back and forth on this, but here's the deal:

* I like Bedstead
* Bedstead is also in the logo

So Bedstead it is! 😤
